//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITowerCafe.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuProductsMap
    {
        public int Id { get; set; }
        public int MenuId { get; set; }
        public int MenuProductId { get; set; }
    
        public virtual MenuProduct MenuProduct { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
